sonar.projectKey=janosmiko_vau
sonar.organization=janosmiko

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**,**/*.gen.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.json

sonar.sourceEncoding=UTF-8
