FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk add --no-cache ca-certificates && \
    adduser -D -h /home/vau vau
COPY vau /usr/local/bin/vau
ENV TERM=xterm-256color
ENV COLORTERM=truecolor
USER vau
ENTRYPOINT ["vau"]
