FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
RUN apk add --no-cache ca-certificates && \
    adduser -D -h /home/vau vau
COPY vau /usr/local/bin/vau
ENV TERM=xterm-256color
ENV COLORTERM=truecolor
USER vau
ENTRYPOINT ["vau"]
